Squashed 'osb-dashboard/' changes from efed84b..dbcf59b
dbcf59b feat(notifications): fixes redirects and adds notifications to different api calls
9314563 fix(backup-details): Fix merge related build errors
adb1a02 Merge branch 'master' of github.com:evoila/cf-service-broker-dashboard
86e9025 feature(auto-scaler): added implementation for current auto scaler backend
809a405 feature(inline-loader): add a component which shows an inline loader on a button
f184494 feature(notification-component): added a notification component for errors/customer information
71ab097 refactor(remove-duplicate-code): in order to have not to much code redundancy I have refactored the Http/EntityServices. All services for components like backup, general, service keys are now passed through the EntityService, which is a generic implementation on top of EntityService
bfd24cf Merge branch 'mysql-upstream'
19a22d7 fix(removed-sample-module): MongoDB contained sample module, which is not necessary --> removed
b4c5e45 fix(generalComponente): fixes errors when page is loaded
fef4d24 fix(dashboard): changes service key creation endpoint to an post request
7eb944b feat(core-http): added ability to add additional custom headers from "outside" of a service
820cbf3 fix(empty-object): fixing main.777d60868591dbeafc84.bundle.js:1 ERROR TypeError: Cannot read property 'service_instance_id' of undefined
89214c4 Merge commit 'a6827fae3b790b8919156234eb3e7f11ff25af3f' into feature/backupapi
b2e494f Merge commit '731b04e80b913adc068f92f2e7a4d670fcb33e88' into feature/backupapi
6311619 Merge commit '1e921cc41b4db1b56f3f00aaae57a3e1f9332fb0' into feature/backupapi
be5fe5b Merge commit '2cc3d5d51df59df64a1769d3ded77831aa16d3a2' into feature/backupapi
c8f37ec fix(remove-upgrade): removed yarn upgrade
5671e91 fix(yarn-goal): Yarn upgrade during build process
1948866 Merge commit 'cf7376df9181e121333825574cc3b97e079e6c28' into feature/backupapi
53826f1 feat(mvn): adds yarn update v0.27.5 info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command. phase to dashboard build
b3f6496 Merge commit 'ea4c728ba4025a4ec5903f52c29ca2b3cc7700f6' into feature/backupapi
8e2eb4f fix(dashboard) fixes build errors

git-subtree-dir: osb-dashboard
git-subtree-split: dbcf59b257582eb07a01137d80cb5121268327ea